import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { useQuery } from "@tanstack/react-query";
import type { Agent, AgentActivity } from "@shared/schema";
import { useState } from "react";
import { BarChart, Activity, TrendingUp, Zap, AlertCircle, Database } from "lucide-react";

export default function Monitoring() {
  const [selectedAgentId, setSelectedAgentId] = useState<string>("");

  // Fetch all agents for selector
  const { data: agents, isLoading: agentsLoading } = useQuery<Agent[]>({
    queryKey: ["/api/agents"],
  });

  // Fetch activity for selected agent
  const { data: activity, isLoading: activityLoading } = useQuery<AgentActivity[]>({
    queryKey: ["/api/agents", selectedAgentId, "activity"],
    enabled: !!selectedAgentId,
  });

  // Calculate totals
  const totals = activity?.reduce(
    (acc, record) => ({
      posts: acc.posts + record.postsGenerated,
      replies: acc.replies + record.repliesSent,
      twitterCalls: acc.twitterCalls + record.twitterApiCalls,
      aiCalls: acc.aiCalls + record.aiModelCalls,
      tokens: acc.tokens + record.tokensUsed,
      errors: acc.errors + record.errorsCount,
    }),
    { posts: 0, replies: 0, twitterCalls: 0, aiCalls: 0, tokens: 0, errors: 0 }
  ) || { posts: 0, replies: 0, twitterCalls: 0, aiCalls: 0, tokens: 0, errors: 0 };

  // Get KB usage stats
  const kbStats = activity?.reduce((acc, record) => {
    const categories = record.kbCategoriesUsed as Record<string, number> || {};
    Object.entries(categories).forEach(([cat, count]) => {
      acc[cat] = (acc[cat] || 0) + count;
    });
    return acc;
  }, {} as Record<string, number>) || {};

  const selectedAgent = agents?.find(a => a.id === selectedAgentId);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold" data-testid="text-page-title">Agent Monitoring</h1>
        <p className="text-sm text-muted-foreground">Track performance metrics and activity</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Select Agent</CardTitle>
          <CardDescription>View detailed metrics for a specific agent</CardDescription>
        </CardHeader>
        <CardContent>
          {agentsLoading ? (
            <Skeleton className="h-10 w-full" />
          ) : (
            <Select value={selectedAgentId} onValueChange={setSelectedAgentId}>
              <SelectTrigger data-testid="select-agent">
                <SelectValue placeholder="Choose an agent..." />
              </SelectTrigger>
              <SelectContent>
                {agents?.map((agent) => (
                  <SelectItem key={agent.id} value={agent.id}>
                    {agent.name} (@{agent.username})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </CardContent>
      </Card>

      {selectedAgentId && (
        <>
          {selectedAgent && (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>{selectedAgent.name}</CardTitle>
                    <CardDescription>@{selectedAgent.username}</CardDescription>
                  </div>
                  <Badge variant={selectedAgent.status === "deployed" ? "default" : "secondary"}>
                    {selectedAgent.status}
                  </Badge>
                </div>
              </CardHeader>
            </Card>
          )}

          {activityLoading ? (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {[1, 2, 3, 4, 5, 6].map((i) => (
                <Skeleton key={i} className="h-32" />
              ))}
            </div>
          ) : activity && activity.length > 0 ? (
            <>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Total Posts</CardTitle>
                    <BarChart className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold" data-testid="metric-posts">{totals.posts}</div>
                    <p className="text-xs text-muted-foreground">Generated by agent</p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Total Replies</CardTitle>
                    <Activity className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold" data-testid="metric-replies">{totals.replies}</div>
                    <p className="text-xs text-muted-foreground">Sent by agent</p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Twitter API Calls</CardTitle>
                    <TrendingUp className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold" data-testid="metric-twitter-calls">{totals.twitterCalls}</div>
                    <p className="text-xs text-muted-foreground">API requests made</p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">AI Model Calls</CardTitle>
                    <Zap className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold" data-testid="metric-ai-calls">{totals.aiCalls}</div>
                    <p className="text-xs text-muted-foreground">Model invocations</p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Tokens Used</CardTitle>
                    <Database className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold" data-testid="metric-tokens">{totals.tokens.toLocaleString()}</div>
                    <p className="text-xs text-muted-foreground">Total tokens consumed</p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Errors</CardTitle>
                    <AlertCircle className="h-4 w-4 text-destructive" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold text-destructive" data-testid="metric-errors">{totals.errors}</div>
                    <p className="text-xs text-muted-foreground">Error count</p>
                  </CardContent>
                </Card>
              </div>

              {Object.keys(kbStats).length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle>Knowledge Base Usage</CardTitle>
                    <CardDescription>Categories used in generations</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      {Object.entries(kbStats)
                        .sort(([, a], [, b]) => b - a)
                        .map(([category, count]) => (
                          <div key={category} className="flex items-center justify-between">
                            <span className="text-sm font-medium capitalize">{category.replace(/_/g, " ")}</span>
                            <Badge variant="secondary">{count} uses</Badge>
                          </div>
                        ))}
                    </div>
                  </CardContent>
                </Card>
              )}

              <Card>
                <CardHeader>
                  <CardTitle>Recent Activity</CardTitle>
                  <CardDescription>Daily breakdown of agent performance</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {activity.slice(0, 10).map((record) => (
                      <div key={record.id} className="flex items-center justify-between p-3 border rounded-lg">
                        <div>
                          <p className="font-medium">{record.date}</p>
                          <p className="text-sm text-muted-foreground">
                            {record.postsGenerated} posts, {record.repliesSent} replies
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-sm font-medium">{record.tokensUsed.toLocaleString()} tokens</p>
                          {record.errorsCount > 0 && (
                            <p className="text-xs text-destructive">{record.errorsCount} errors</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </>
          ) : (
            <Card>
              <CardContent className="pt-6">
                <div className="text-center py-8 text-muted-foreground">
                  <Activity className="h-12 w-12 mx-auto mb-3 opacity-50" />
                  <p>No activity data available for this agent yet.</p>
                  <p className="text-xs mt-1">Activity will be tracked when the agent is deployed and active.</p>
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}

      {!selectedAgentId && (
        <Card>
          <CardContent className="pt-6">
            <div className="text-center py-8 text-muted-foreground">
              <BarChart className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p>Select an agent to view monitoring data</p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
